//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace noaa_parse
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeatherObservation
    {
        public int WeatherObservationID { get; set; }
        public Nullable<double> Elevation { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Temperature { get; set; }
        public string TemperatureLabel { get; set; }
        public Nullable<int> DewPoint { get; set; }
        public Nullable<int> RelativeHumidity { get; set; }
        public Nullable<int> WindSpeed { get; set; }
        public Nullable<int> WindDirection { get; set; }
        public Nullable<int> WindGust { get; set; }
        public string WeatherText { get; set; }
        public string Icon { get; set; }
        public Nullable<double> Visibility { get; set; }
        public Nullable<double> Altimeter { get; set; }
        public Nullable<double> Barometer { get; set; }
        public Nullable<int> WindChill { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
