//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace noaa_parse
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeatherForecast
    {
        public int WeatherForecastID { get; set; }
        public string ForecastWhen { get; set; }
        public string TemperatureLabel { get; set; }
        public Nullable<int> Temperature { get; set; }
        public Nullable<int> PercPrecip { get; set; }
        public string WeatherTitle { get; set; }
        public string WeatherText { get; set; }
        public string Icon { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
